"""Prompt templates and system prompts."""

from prompts.system_prompts import (
    MAIN_SYSTEM_PROMPT,
    REACT_SYSTEM_PROMPT,
    STRUCTURED_OUTPUT_PROMPT,
)
from prompts.tool_prompts import (
    WEB_SEARCH_PROMPT,
    WIKIPEDIA_PROMPT,
    ARXIV_PROMPT,
    CODE_EXECUTION_PROMPT,
)
from prompts.templates import (
    ANSWER_EXTRACTION_TEMPLATE,
    TOOL_SELECTION_TEMPLATE,
    VALIDATION_TEMPLATE,
)

__all__ = [
    "MAIN_SYSTEM_PROMPT",
    "REACT_SYSTEM_PROMPT",
    "STRUCTURED_OUTPUT_PROMPT",
    "WEB_SEARCH_PROMPT",
    "WIKIPEDIA_PROMPT",
    "ARXIV_PROMPT",
    "CODE_EXECUTION_PROMPT",
    "ANSWER_EXTRACTION_TEMPLATE",
    "TOOL_SELECTION_TEMPLATE",
    "VALIDATION_TEMPLATE",
]

